"""Add overall_rating and other missing columns to PlayerRating

Revision ID: 5078756f1422
Revises: ad5cc0037d62
Create Date: 2025-07-23 12:43:11.407666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5078756f1422'
down_revision = 'ad5cc0037d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overall_rating', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('speed_rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shot_rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pass_rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('feel_rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('heading_rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('powershot_rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('defense_ai_rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('physicality_rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('review_text', sa.Text(), nullable=True))
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.INTEGER(), nullable=False))
        batch_op.drop_column('review_text')
        batch_op.drop_column('physicality_rating')
        batch_op.drop_column('defense_ai_rating')
        batch_op.drop_column('powershot_rating')
        batch_op.drop_column('heading_rating')
        batch_op.drop_column('feel_rating')
        batch_op.drop_column('pass_rating')
        batch_op.drop_column('shot_rating')
        batch_op.drop_column('speed_rating')
        batch_op.drop_column('overall_rating')

    # ### end Alembic commands ###
