"""Remove email confirmation fields from User model

Revision ID: ad5cc0037d62
Revises: d3c464feaa07
Create Date: 2025-07-23 09:20:25.889253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5cc0037d62'
down_revision = 'd3c464feaa07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_confirmed_on')
        batch_op.drop_column('email_confirmed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmed', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('email_confirmed_on', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
