"""init push token and coupon seen

Revision ID: fbb6c9e0f113
Revises: 83ed559baa88
Create Date: 2025-12-21 13:00:38.966401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb6c9e0f113'
down_revision = '83ed559baa88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon_seen', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('first_seen_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.create_unique_constraint('uq_coupon_seen_code', ['code'])

    with op.batch_alter_table('push_token', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=False)
        batch_op.alter_column('is_enabled',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('coupons_enabled',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('mode',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'instant'"))
        batch_op.drop_column('platform')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.VARCHAR(length=16), nullable=True))
        batch_op.alter_column('mode',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'instant'"))
        batch_op.alter_column('coupons_enabled',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('is_enabled',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('token',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('coupon_seen', schema=None) as batch_op:
        batch_op.drop_constraint('uq_coupon_seen_code', type_='unique')
        batch_op.alter_column('first_seen_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('code',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
